import type { NextPage } from 'next'
import Head from 'next/head'
import { NavBar } from '../components/Navbar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Buug Tracker</title>
        <meta name="Bug tracker web application" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
    </div>
  )
}

export default Home
