import type { NextPage } from 'next'
import Head from 'next/head'
import { NavbarLogout } from '../components/NavbarLogout'
import { Section } from '../components/Section'
import { useUser } from '@auth0/nextjs-auth0'
import { NavbarLogin } from '../components/NavbarLogin'
import favicon from '../public/favicon.ico'

const Home: NextPage = () => {
  const { user, error, isLoading } = useUser();

  if (isLoading) return <div>Loading...</div>

  if (error) return <div>{error.message}</div>

  if (user) {
    return (
      <div>
        <Head>
          <title>Buug-Issue Tracker</title>
          <meta name="Bug tracker web application" content="Generated by create next app" />
          <link rel="icon" type="image/x-icon" href={favicon.src} />
        </Head>
  
        <NavbarLogout />
        <Section />
      </div>
    )
  }

  return (
    <div>
      <Head>
        <title>Buug Tracker</title>
        <meta name="Bug tracker web application" content="Generated by create next app" />
        <link rel="icon" type="image/x-icon" href={favicon.src} />
      </Head>

      <NavbarLogin />
      <Section />
    </div>
  )
}

export default Home